### ISSUE TITLE
Please drop libcurl 7 builds 

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/azure-core-cpp-feedstock#19]
Same as https://github.com/conda-forge/tiledb-feedstock/issues/240, please remove the `conda_build_config.yaml` overrides here.

CC @jdblischak

**Comment by jdblischak** [comment]
This feedstock has no `conda_build_config.yaml`. We removed the extra openssl/libcurl variants back in February (#16).

I searched the repo for ["libcurl"](https://github.com/search?q=repo%3Aconda-forge%2Fazure-core-cpp-feedstock%20libcurl&type=code), and I couldn't find any remaining trace of libcurl 7. All the YAML files in `.ci_support/` have libcurl 8.

I apologize if I am missing something obvious. If there are additional steps I still need to take, please re-open this Issue.

**Comment by h-vetinari** [comment]
Hm, apologies for the false alarm. I was convinced yesterday that I had seen this in this repo here; serves me right for not adding a reference to the commit or lines in question.
